# Generated by Django 4.2.8 on 2024-09-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Категорию", "verbose_name_plural": "Категории"},
        ),
        migrations.AddField(
            model_name="categories",
            name="name",
            field=models.CharField(
                default=2, max_length=150, unique=True, verbose_name="Название"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Слаг - дописка в URL",
            ),
        ),
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Слаг - дописка в URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="goods_images",
                        verbose_name="щя фотограф сгоняет за фото",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=7, verbose_name="Цена"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=3,
                        verbose_name="Скидка в %",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Кол-во"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.categories",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товарiщ",
                "db_table": "product",
            },
        ),
    ]
